version: "3"

services:
  postgres:
    image: postgres:12.3
    env_file:
      - ./src/.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - back

volumes:
  postgres:

networks:
  back: