// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/apm-dev/go-clean-architecture/data/datasources/acl_service"
	"github.com/apm-dev/go-clean-architecture/data/repositories"
	"github.com/apm-dev/go-clean-architecture/domain/usecases"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CheckAccess() usecases.CheckAccess {
	aclDataSource := acl_service.NewACLDataSource()
	repositoriesACLRepository := repositories.NewACLRepository(aclDataSource)
	checkAccess := usecases.NewCheckAccess(repositoriesACLRepository)
	return checkAccess
}

// wire.go:

var (

	//	DataSources
	aclDS = wire.NewSet(acl_service.NewACLDataSource)

	//	Repositories
	aclRepository = wire.NewSet(repositories.NewACLRepository, aclDS)

	//	UseCases
	checkAccessUC = wire.NewSet(usecases.NewCheckAccess, aclRepository)
)
