// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pbs/blog.proto

package pbs

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Blog) Validate() error {
	return nil
}
func (this *CreateBlogRequest) Validate() error {
	if !(len(this.Title) > 3) {
		return github_com_mwitkow_go_proto_validators.FieldError("Title", fmt.Errorf(`value '%v' must have a length greater than '3'`, this.Title))
	}
	if !(len(this.Title) < 128) {
		return github_com_mwitkow_go_proto_validators.FieldError("Title", fmt.Errorf(`value '%v' must have a length smaller than '128'`, this.Title))
	}
	if !(len(this.Content) > 5) {
		return github_com_mwitkow_go_proto_validators.FieldError("Content", fmt.Errorf(`value '%v' must have a length greater than '5'`, this.Content))
	}
	return nil
}
func (this *CreateBlogResponse) Validate() error {
	if this.Blog != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Blog); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Blog", err)
		}
	}
	return nil
}
