// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	errors "github.com/apm-dev/go-clean-architecture/core/errors"
	mock "github.com/stretchr/testify/mock"

	models "github.com/apm-dev/go-clean-architecture/data/models"
)

// PgDataSource is an autogenerated mock type for the PgDataSource type
type PgDataSource struct {
	mock.Mock
}

// CreateTables provides a mock function with given fields:
func (_m *PgDataSource) CreateTables() *errors.Error {
	ret := _m.Called()

	var r0 *errors.Error
	if rf, ok := ret.Get(0).(func() *errors.Error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errors.Error)
		}
	}

	return r0
}

// InsertBlog provides a mock function with given fields: _a0
func (_m *PgDataSource) InsertBlog(_a0 *models.BlogModel) (int64, *errors.Error) {
	ret := _m.Called(_a0)

	var r0 int64
	if rf, ok := ret.Get(0).(func(*models.BlogModel) int64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 *errors.Error
	if rf, ok := ret.Get(1).(func(*models.BlogModel) *errors.Error); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.Error)
		}
	}

	return r0, r1
}
