// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	errors "github.com/apm-dev/go-clean-architecture/core/errors"
	entities "github.com/apm-dev/go-clean-architecture/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// ACLRepository is an autogenerated mock type for the ACLRepository type
type ACLRepository struct {
	mock.Mock
}

// HasAccess provides a mock function with given fields: id, m
func (_m *ACLRepository) Call(id entities.UserID, m entities.Method) (bool, *errors.Error) {
	ret := _m.Called(id, m)

	var r0 bool
	if rf, ok := ret.Get(0).(func(entities.UserID, entities.Method) bool); ok {
		r0 = rf(id, m)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 *errors.Error
	if rf, ok := ret.Get(1).(func(entities.UserID, entities.Method) *errors.Error); ok {
		r1 = rf(id, m)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.Error)
		}
	}

	return r0, r1
}
